WARN: prepare
It seems that your USE_PYTHON setting lists different Python
implementations than your PYTHON_TARGETS variable. Please consider
using the following value instead:

	USE_PYTHON='[35m3.4 [1m2.7[0m'

Please note that after changing the USE_PYTHON variable, you may need
to run 'python-updater' to rebuild affected packages.

For more information on PYTHON_TARGETS and python.eclass
compatibility, please see the relevant Wiki article [1].

[1] https://wiki.gentoo.org/wiki/Project:Python/PYTHON_TARGETS
